version: '3.1'

services:
  inventory_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: inventory
      POSTGRES_USER: inventory
      POSTGRES_DB: inventory
    ports:
      - 2346:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
